# Generated by Django 4.2.1 on 2023-06-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesmodel',
            name='slug',
            field=models.TextField(default='fallout-new-vegas--ultimate-edition'),
            preserve_default=False,
        ),
    ]
