# Generated by Django 4.2.1 on 2023-06-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackmodel',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
